version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "wallet"
      POSTGRES_USER: "vova1"
      POSTGRES_PASSWORD: "1231234"
    ports:
      - "5432:5432"